#!bin/bash

ssh-keygen -t rsa -b 4096 -C "e-mail" 
# enter password 2x afterwards optional
# enter file location, "Enter" for default

cat id_rsa.pub             # copy this and paste it on your github profile/ the repo itself
exec ssh-agent bash        # or zsh depending on shell
ssh-add id_rsa             # done in the ~/.ssh folder
git init
git config --global user.name " "
git config --global user.email " "
git remote add origin git@github.com:user-name/repo-name

#ensure the branch is correct, use git switch if needed

git add .
git commit -m "message here"
git push
